name: Call a reusable workflow

on:
  push:
    branches:
      - master

jobs:
  call-workflow-passing-data:
    uses: Security/.github/workflows/base.yml@master
    with:
      username: mona
      secrets:
        token: ${{ secrets.TOKEN }}