name: Call a reusable workflow

on:
  push:
    branches: [ master ]
    paths: 
          - 'force-app/**'
  workflow_dispatch:
    inputs:
      ref:
        description: "commitId"
        required: true
        default: ""

jobs:
  callWorkflowDeploySourceToSalesforce:
    uses: ssspure/Security/.github/workflows/base.yml@master
    with:
      commitId: github.event.inputs.ref
      packageXml: partialPackage.xml
      triggerEvent: ${{ github.event_name }}
    secrets:
      token: ${{ secrets.SALESFORCEAUTHINFO }}