# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Deploy Source to Salesforce
on:
  push:
    branches: [ master ]
    paths:
            - 'force-app/**'
  pull_request:
    branches: [ master ]
    paths:
            - 'force-app/**'  
  workflow_dispatch:
    branches: [ master ]  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout Source from Github
      - name: 'Checkout source code'
        uses: actions/checkout@v2
   
      # Install Salesforce CLI
      - name: 'Install Salesforce CLI'
        run: |
            wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
            mkdir ~/sfdx
            tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
            echo "$HOME/sfdx/bin" >> $GITHUB_PATH
            ~/sfdx/bin/sfdx version

      # Store secret for dev hub
      - name: 'Populate auth file with SFDX_URL secret'
        shell: bash
        run: 'echo ${{ secrets.SALESFORCEAUTHINFO }} > SFDX_AUTH_INFO'

      # Authenticate against dev hub
      - name: 'Authenticate against dev hub'
        run: sfdx force:auth:sfdxurl:store -f SFDX_AUTH_INFO -s -a AUTH_INFO

      # - name: Run Apex test
      #   shell: bash
      #   run: |
      #     sudo cat manifest/package_diff.xml | grep -o -P '<members>[A-Za-z0-9]*Test[s]*</members>' | sed 's/<members>//g' | sed 's/<\/members>//g' | tr '\n' ',' | sed s/,$// > TEST_CLASS
      #     node_modules/sfdx-cli/bin/run force:apex:test:run --resultformat tap --codecoverage -c -r human -n $(cat TEST_CLASS)

      # - name: Deploy source
      #   id: Deploy
      #   if: github.event_name == 'push'
      #   run:
      #     node_modules/sfdx-cli/bin/run force:source:deploy -x manifest/package_diff.xml -u AUTH_INFO --json --loglevel fatal

      # - name: Run Apex test
      #   shell: bash
      #   run: |
      #     sudo cat manifest/package_diff.xml | grep -o -P '<members>[A-Za-z0-9]*Test[s]*</members>' | sed 's/<members>//g' | sed 's/<\/members>//g' | tr '\n' ',' | sed s/,$// > TEST_CLASS
      #     node_modules/sfdx-cli/bin/run force:apex:test:run --resultformat tap --codecoverage -c -r human -n $(cat TEST_CLASS)

      - name: Get All Testclass from package xml
        shell: bash
        if: github.event_name == 'push'
        run: |
          sudo cat manifest/package_diff.xml | grep '<members>[A-Za-z0-9]*Test[s]*<//members>' > TEST_CLASS
          cat ./TEST_CLASS


      - name: Deploy source And Run Apex Test
        id: Deploy
        shell: bash
        if: github.event_name == 'push'
        run: |
          sfdx force:source:deploy -x manifest/package_diff.xml -u AUTH_INFO --json --loglevel fatal --testlevel NoTestRun
